name: Meticulous

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

permissions:
  actions: write
  checks: write
  contents: read
  discussions: write
  pull-requests: write
  statuses: write

jobs:
  test:
    name: Report diffs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Serve website
        run: |
          hugo
          hugo -F --i18n-warnings --bind 0.0.0.0 server &
          sleep 5

      - name: Run Meticulous tests
        uses: alwaysmeticulous/report-diffs-action@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          app-url: "http://localhost:1313/"
